version: "3.9"
services:
  nginx:
    image: "nginx:latest"
    volumes:
      - /host/path/nginx.conf:/etc/nginx/nginx.conf:ro
  api-gateway:
    build: .
    ports:
      - "80:8080"
  authentication:
    build: .
    ports:
      - "80:8080"
  postgresql:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yuruojie
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  redis:
    image: "redis:alpine"